name: CI

on:
  push:
    branches: [ 2.x ]
  schedule:
    - cron: '0 12 * * *'

jobs:
  translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Extract translations
        uses: Szpadel/magento-l18n-extractor-action@v1
        with:
          output_file_path: i18n/source.csv
      
      - name: Sync Translations
        uses: crowdin/github-action@1.0.9
        with:
          download_translations: true
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          config: crowdin.yml
          crowdin_branch_name: ${{ github.event.repository.name }}-${{ github.ref }}
          pull_request_title: "Update translations"
        env:
          GITHUB_TOKEN: ${{ github.token }}
